// Post-build: mirror each page's <link rel="preload"> tags into Link headers
// appended to dist/_headers. Cloudflare turns Link headers into 103 Early
// Hints, so the font / hero image start downloading before the HTML arrives.
// Runs after `astro build` (see the build script in package.json) because the
// hashed /_astro/ filenames only exist once the build has finished.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'

const DIST = resolve(process.cwd(), 'dist')
const MARKER = '# Early hints (generated by scripts/early-hints.ts, do not edit)'

async function htmlFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await htmlFiles(path)))
    else if (entry.name.endsWith('.html')) files.push(path)
  }
  return files
}

function parseAttrs(tag: string): Record<string, string> {
  const attrs: Record<string, string> = {}
  for (const m of tag.matchAll(/([a-z-]+)(?:="([^"]*)")?/g)) {
    attrs[m[1]] = m[2] ?? ''
  }
  return attrs
}

// The Link header needs a single URL even for responsive preloads; use the
// 520w variant (the same fallback the <img> src uses) when there's no href.
function srcsetFallback(srcset: string): string | undefined {
  const entries = srcset.split(',').map((s) => s.trim().split(/\s+/))
  const at520 = entries.find(([, d]) => d === '520w')
  return (at520 ?? entries[entries.length - 1])?.[0]
}

function toLinkHeader(attrs: Record<string, string>): string | undefined {
  if (attrs.rel !== 'preload') return undefined
  const href = attrs.href ?? (attrs.imagesrcset && srcsetFallback(attrs.imagesrcset))
  if (!href) return undefined
  const params = [`rel=preload`, `as=${attrs.as}`]
  if (attrs.type) params.push(`type=${attrs.type}`)
  if (attrs.imagesrcset) params.push(`imagesrcset="${attrs.imagesrcset}"`)
  if (attrs.imagesizes) params.push(`imagesizes="${attrs.imagesizes}"`)
  if ('crossorigin' in attrs) params.push('crossorigin')
  return `<${href}>; ${params.join('; ')}`
}

const lines: string[] = ['', MARKER]
for (const file of await htmlFiles(DIST)) {
  const html = await readFile(file, 'utf8')
  const head = html.slice(0, html.indexOf('</head>'))
  const headers = [...head.matchAll(/<link\b[^>]*>/g)]
    .map((m) => toLinkHeader(parseAttrs(m[0])))
    .filter((h): h is string => Boolean(h))
  if (headers.length === 0) continue

  const route = '/' + relative(DIST, file).split(sep).join('/').replace(/index\.html$/, '')
  // Cover the path both with and without its trailing slash.
  const routes = route === '/' ? [route] : [route, route.replace(/\/$/, '')]
  for (const r of routes) {
    lines.push(r)
    for (const h of headers) lines.push(`  Link: ${h}`)
  }
}

const headersPath = join(DIST, '_headers')
const existing = (await readFile(headersPath, 'utf8')).split('\n' + MARKER)[0].trimEnd()
await writeFile(headersPath, existing + '\n' + lines.join('\n') + '\n')
console.log(`early-hints: appended Link headers to dist/_headers`)
